Repository Team-PalPalHae-Dealight/Team-PalPalHae-Dealight-FE, pull requests merged in 2023-12, with the labels that each got.

#274 영업 준비 중인 업체의 캐시 데이터 삭제 로직 추가
  README.md
  app/(main)/customer/cart/[id]/_components/item-card/ItemCard.tsx
  app/(main)/customer/home/_components/ItemCards.tsx
  app/(main)/customer/item-detail/[id]/_components/ItemDetail.tsx
  app/(main)/customer/order-detail/[id]/_components/product-list/ProductList.tsx
  app/(main)/customer/search/_component/Itemcard/Itemcard.tsx
  app/(main)/customer/store-detail/[id]/_components/ItemCards.tsx
  app/(main)/customer/store-detail/[id]/_components/StoreDetail.tsx
  app/(main)/store/home/_components/main-contents/MainContents.tsx
  app/(main)/store/home/_components/product-list/ItemCards.tsx
  app/(main)/store/home/_components/product-list/OpenStoreItems.tsx
  app/(main)/store/home/_components/product-list/ProductList.tsx
  app/(main)/store/item-manage/[id]/_components/ItemCards.tsx
  app/(main)/store/item-register/_components/ItemRegister.tsx
  app/(main)/store/my-page/[id]/_components/image-uploader/ImageUploader.tsx
  app/(main)/store/order-detail/[id]/_components/main-contents/MainContents.tsx
  app/(main)/store/order-detail/[id]/_components/product-list/ProductList.tsx
  app/(main)/store/store-manage/_components/ItemCards.tsx
  app/(main)/store/store-manage/_components/StoreManage.tsx
  app/_components/pop-up/CustomPopUp.tsx
  app/_components/pop-up/PopUp.tsx
Labels: 버그, 기능, 긴급, 리팩토링

#279 장바구니 react query 적용
  app/(main)/customer/cart/[id]/_components/cart-contents/CartContents.tsx
  app/(main)/customer/cart/[id]/_components/item-card/ItemCard.stories.tsx
  app/(main)/customer/cart/[id]/_components/item-card/ItemCard.tsx
  app/(main)/customer/cart/[id]/_components/item-list/ItemList.stories.tsx
  app/(main)/customer/cart/[id]/_components/item-list/ItemList.tsx
  app/(main)/customer/cart/[id]/_components/main-contents/MainContents.tsx
  app/(main)/customer/cart/[id]/_components/order-information/OrderInformation.tsx
  app/(main)/customer/cart/[id]/_services/deleteCart.ts
  app/(main)/customer/cart/[id]/_services/getCart.ts
  app/(main)/customer/cart/[id]/_services/patchCart.ts
  app/(main)/customer/cart/[id]/_types/CartType.ts
  app/(main)/customer/cart/[id]/_utils/sumTotalPrice.ts
  app/_hooks/query/cart.ts
  app/_hooks/query/member.ts
  app/_hooks/query/order.ts
Labels: 리팩토링

#284 주문하기 react query 적용하기
  app/(main)/customer/cart/[id]/_components/cart-contents/CartContents.tsx
  app/_hooks/query/order.ts
  app/page.tsx
Labels: 기능, 리팩토링

#282 상품 디자인 및 레이아웃 수정
  app/(main)/customer/cart/[id]/_components/item-list/ItemList.stories.tsx
  app/(main)/customer/item-detail/[id]/_components/ItemDetail.tsx
  app/(main)/store/item-detail/[id]/_components/ItemDetail.tsx
  app/(main)/store/item-edit/[id]/_components/ItemEdit.tsx
  app/(main)/store/item-register/_components/ItemRegister.tsx
  app/_constants/img.ts
  app/_providers/AuthProvider.tsx
Labels: 스타일, 리팩토링

#280 qa 진행 작업
  app/(main)/store/item-edit/[id]/_components/ItemEdit.tsx
  app/(main)/store/item-register/_components/ItemRegister.tsx
  app/_components/AddressButton/AddressButton.tsx
Labels: 버그, 리팩토링

#286 마이페이지 닉네임 중복 기능 추가하기
  app/(main)/customer/item-detail/[id]/_components/BottomButtons.tsx
  app/(main)/customer/my-page/[id]/_components/MyPageContents/MyPageContents.tsx
  app/_components/main/StartLink.tsx
  app/_hooks/query/member.ts
  app/_hooks/query/order.ts
  app/page.tsx
Labels: 스타일, 기능, 긴급, 리팩토링

#288 빠뜨린 로직 추가하기
  app/(main)/customer/cart/[id]/_components/cart-contents/CartContents.tsx
  app/(main)/customer/cart/[id]/_components/item-card/ItemCard.tsx
  app/(main)/customer/cart/[id]/_services/clearCart.ts
  app/(main)/customer/cart/[id]/_services/postOrder.ts
  app/_hooks/query/cart.ts
Labels: 기능, 긴급, 리팩토링
