Repository Team-PalPalHae-Dealight/Team-PalPalHae-Dealight-FE, pull requests merged in 2023-10, with the labels that each got.

#7 eslint, prettier 초기 세팅
  .eslintrc.json
  .prettierrc
  package-lock.json
  package.json
Labels: 문서, 기능

#6 5 스토리북 관련 작업
  .eslintrc.json
  .github/workflows/deploy.yml
  .github/workflows/pull_request.yml
  .storybook/main.ts
  .storybook/preview.ts
  app/stories/Temp.stories.tsx
  app/stories/Temp.tsx
  build-storybook.log
  package-lock.json
  package.json
Labels: 기능

#8 폴더 구조 정리하기
  .vscode/setting.json
  app/_components/primaryButton/primaryButton.tsx
  app/_config/_image/assets.ts
  app/_constants/common.ts
  app/_hooks/useValidationToken.ts
  app/_services/auth/auth.ts
  app/_storybooks/button/primaryButton.stories.ts
  app/_types/type.ts
Labels: 기능

#10 husky 초기 세팅
  .husky/pre-commit
  package-lock.json
  package.json
Labels: 기능

#15 배포 관련 작업
  .github/workflows/deploy.yml
  .github/workflows/pull_request.yml
  README.md
  app/_storybooks/button/primaryButton.stories.ts
  app/_storybooks/button/primaryButton.stories.tsx
  app/page.tsx
Labels: 기능

#14 tailwindcss plugin 설치 및 prettier 추가 설정
  .prettierignore
  .prettierrc
  .vscode/setting.json
  package-lock.json
  package.json
  prettier.config.js
Labels: 문서, 기능

#22 footer 컴포넌트 작업
  .prettierrc
  .storybook/preview.ts
  app/_components/Footer/Footer.tsx
  app/_components/Footer/FooterItem.tsx
  app/_components/Footer/assets/home.svg
  app/_components/Footer/assets/mypage.svg
  app/_components/Footer/assets/order.svg
  app/globals.css
  app/stories/footer.stories.tsx
Labels: 스타일, 기능

#26 pretendard regular font global 적용
  app/_constants/common.ts
  app/_constants/font.tsx
  app/layout.tsx
  public/fonts/Pretendard-Regular.woff2
Labels: 스타일, 기능

#24 시작 화면 버튼 컴포넌트 작업
  .storybook/main.ts
  .storybook/preview.ts
  .vscode/setting.json
  .vscode/settings.json
  app/_components/main-temp/_components/StartLink.stories.tsx
  app/_components/main-temp/_components/StartLink.tsx
  app/_storybooks/button/primaryButton.stories.tsx
  app/globals.css
  app/page.tsx
  app/stories/Temp.stories.tsx
  app/stories/Temp.tsx
  public/shop-main.png
  public/user-main.png
Labels: 스타일, 기능

#23 feat: router 설정
  app/(main)/custumer/cart/[id]/page.tsx
  app/(main)/custumer/home/page.tsx
  app/(main)/custumer/login/page.tsx
  app/(main)/custumer/my-page/[id]/page.tsx
  app/(main)/custumer/order-detail/[id]/page.tsx
  app/(main)/custumer/order-list/[id]/page.tsx
  app/(main)/custumer/order-product/[id]/page.tsx
  app/(main)/custumer/review-write/[id]/page.tsx
  app/(main)/custumer/review/[id]/page.tsx
  app/(main)/custumer/search/[keyword]/page.tsx
  app/(main)/custumer/sign-up/page.tsx
  app/(main)/custumer/store-detail/[id]/page.tsx
  app/(main)/store/edit-product/[id]/page.tsx
  app/(main)/store/home/page.tsx
  app/(main)/store/login/page.tsx
  app/(main)/store/my-page/[id]/page.tsx
  app/(main)/store/order-detail/[id]/page.tsx
  app/(main)/store/order-list/[id]/page.tsx
  app/(main)/store/product-detail/[id]/page.tsx
  app/(main)/store/register-product/page.tsx
  app/(main)/store/sign-up/page.tsx
  app/(main)/store/store-manage/[id]/page.tsx
  app/_constants/route.ts
Labels: 기능

#35 스토리북 배포 경로 에러 작업
  .storybook/main.ts
  app/_assets/images/shop-main.png
  app/_assets/images/user-main.png
  app/_assets/svgs/.temp
  app/_components/main-temp/_components/StartLink.tsx
Labels: 버그

#44 husky 적용 안되는 문제 해결
  .husky/pre-commit
  package.json
Labels: 버그

#32 Footer컴포넌트 리팩토링
  .storybook/main.ts
  app/_components/Footer/Footer.tsx
  app/_components/Footer/FooterItem.tsx
  app/_components/Footer/footer.stories.tsx
  app/page.tsx
  next.config.js
  package-lock.json
  package.json
Labels: 리팩토링

#37 PrimaryButton 컴포넌트 구현
  app/_components/PrimaryButton/PrimaryButton.stories.tsx
  app/_components/PrimaryButton/PrimaryButton.tsx
  app/_components/primaryButton/primaryButton.tsx
Labels: 스타일, 기능

#36 배너 및 카카오 로그인 컴포넌트 작업
  .vscode/stories.tsx.code-snippets
  app/_assets/images/banner.png
  app/_assets/images/kakao.png
  app/_components/main-temp/_components/KakaoButton.stories.tsx
  app/_components/main-temp/_components/KakaoButton.tsx
Labels: 스타일, 기능

#34 msw 작업
  .env.local.example
  app/_components/main-temp/_components/MswTestButton.tsx
  app/_mocks/browser.js
  app/_mocks/handlers/handler.ts
  app/_mocks/handlers/temp.ts
  app/_mocks/server.js
  app/layout.tsx
  app/page.tsx
  package-lock.json
  package.json
  public/mockServiceWorker.js
  public/mocks/MSWComponent.tsx
  public/mocks/index.ts
Labels: 기능

#45 색상 변수 정의하기
  package-lock.json
  package.json
  tailwind.config.ts
Labels: 기능

#40 refactor: custumer 오타 수정
  app/(main)/custumor/cart/[id]/page.tsx
  app/(main)/custumor/home/page.tsx
  app/(main)/custumor/login/page.tsx
  app/(main)/custumor/my-page/[id]/page.tsx
  app/(main)/custumor/order-detail/[id]/page.tsx
  app/(main)/custumor/order-list/[id]/page.tsx
  app/(main)/custumor/order-product/[id]/page.tsx
  app/(main)/custumor/review-write/[id]/page.tsx
  app/(main)/custumor/review/[id]/page.tsx
  app/(main)/custumor/search/[keyword]/page.tsx
  app/(main)/custumor/sign-up/page.tsx
  app/(main)/custumor/store-detail/[id]/page.tsx
Labels: 리팩토링

#46 크로마틱 관련 기능 설정
  .github/workflows/pull_request.yml
  .vscode/settings.json
Labels: 기능

#48 footer, primarybutton 컴포넌트 색상 변수 설정 및 hover 삭제
  app/_components/Footer/Footer.tsx
  app/_components/Footer/FooterItem.tsx
  app/_components/PrimaryButton/PrimaryButton.tsx
Labels: 리팩토링

#53 refactor: customer 오타 수정
  app/(main)/customer/cart/[id]/page.tsx
  app/(main)/customer/home/page.tsx
  app/(main)/customer/login/page.tsx
  app/(main)/customer/my-page/[id]/page.tsx
  app/(main)/customer/order-detail/[id]/page.tsx
  app/(main)/customer/order-list/[id]/page.tsx
  app/(main)/customer/order-product/[id]/page.tsx
  app/(main)/customer/review-write/[id]/page.tsx
  app/(main)/customer/review/[id]/page.tsx
  app/(main)/customer/search/[keyword]/page.tsx
  app/(main)/customer/sign-up/page.tsx
  app/(main)/customer/store-detail/[id]/page.tsx
  app/_components/Header/Header.tsx
  app/_components/Header/HeaderItem.tsx
  app/_components/Header/HeaderItemtext.tsx
  app/_components/Header/assets/Polygon.svg
  app/_components/Header/assets/cart.svg
  app/_components/Header/assets/search.svg
  app/_constants/route.ts
Labels: 리팩토링

#50 주소 찾기 컴포넌트 작업 완료
  app/_components/SearchAddress/SearchAddress.tsx
  package-lock.json
  package.json
Labels: 기능
