Repository Team-PalPalHae-Dealight/Team-PalPalHae-Dealight-FE, pull requests merged in 2023-11, with the labels that each got.

#55 footer primarybutton font size 수정
  app/_components/Footer/Footer.tsx
  app/_components/Footer/FooterItem.tsx
  app/_components/Footer/footer.stories.tsx
  app/_components/PrimaryButton/PrimaryButton.stories.tsx
  app/_components/PrimaryButton/PrimaryButton.tsx
Labels: 스타일

#59 시작 페이지 및 로그인 페이지 작업
  .husky/pre-commit
  app/(main)/customer/login/page.tsx
  app/(main)/store/login/page.tsx
  app/_assets/images/dealight-intro-1.png
  app/_assets/images/dealight-intro-2.png
  app/_assets/images/dealight-intro-3.png
  app/_assets/images/kakao.png
  app/_assets/images/shop-main.png
  app/_assets/images/user-main.png
  app/_components/PrimaryButton/PrimaryButton.tsx
  app/_components/main-temp/MswTestButton.tsx
  app/_components/main-temp/ServiceIntro.stories.tsx
  app/_components/main-temp/ServiceIntro.tsx
  app/_components/main-temp/StartLink.stories.tsx
  app/_components/main-temp/StartLink.tsx
  app/_components/main-temp/_components/KakaoButton.stories.tsx
  app/_components/main-temp/_components/KakaoButton.tsx
  app/_components/main-temp/_components/StartLink.tsx
  app/_constants/route.ts
  app/globals.css
  app/layout.tsx
  app/page.tsx
  package-lock.json
  package.json
  public/mocks/index.ts
Labels: 스타일, 기능

#61 feat: middleware 리다이렉트 구현
  middleware.ts
Labels: 기능

#66 위도 경도 구하는 작업
  .gitignore
  app/_components/AddressButton/AddressButton.stories.tsx
  app/_components/AddressButton/AddressButton.tsx
  app/_components/SearchAddress/SearchAddress.tsx
  app/_hooks/useCoordinate.ts
  app/_hooks/useValidationToken.ts
  app/_types/kakaoMap.ts
  app/_types/type.ts
  app/layout.tsx
  package-lock.json
  package.json
Labels: 기능

#67 지도 관련 세팅 작업
  .env.local.example
  app/(main)/customer/home/page.tsx
  app/_components/KakaoMap/KakaoMap.tsx
  app/_hooks/kakao-map/useGetCurrentMarker.ts
  app/_hooks/kakao-map/useGetMap.ts
  app/_hooks/kakao-map/useGetMarker.ts
  app/layout.tsx
  app/page.tsx
  public/mocks/MSWComponent.tsx
Labels: 기능

#73 api 연결 테스트 작업
  .env.local.example
  app/page.tsx
Labels: 긴급

#80 63 업체 등록하기 팝업창 작업
  app/(main)/store/home/_components/register-modal/RegisterModal.stories.tsx
  app/(main)/store/home/_components/register-modal/RegisterModal.tsx
  app/(main)/store/home/page.tsx
  app/_constants/route.ts
Labels: 기능

#79 무한스크롤 구현
  app/_components/infinite-scroll/InfiniteScrollList.stories.tsx
  app/_components/infinite-scroll/InfiniteScrollList.tsx
  app/_components/infinite-scroll/Items.tsx
  app/_components/infinite-scroll/LoadMoreItems.tsx
  app/_components/infinite-scroll/fetchData.ts
  app/_components/spinner/Spinner.tsx
  package-lock.json
  package.json
Labels: 기능

#75 feat: baseurl 상수 설정 완료
  app/_constants/baseurl.ts
Labels: 기능

#78 feat: 로컬 스토리지 함수 작성
  .vscode/settings.json
  app/_utils/localstorage.ts
Labels: 기능

#83 (수정 완료)업체 등록하기 페이지 작업
  app/(main)/store/home/_components/register-modal/RegisterModal.tsx
  app/(main)/store/home/page.tsx
  app/(main)/store/register-store/_components/store-info-form/StoreInfoForm.stories.tsx
  app/(main)/store/register-store/_components/store-info-form/StoreInfoForm.tsx
  app/(main)/store/register-store/_components/store-num-form/StoreNumForm.stories.tsx
  app/(main)/store/register-store/_components/store-num-form/StoreNumForm.tsx
  app/(main)/store/register-store/_components/store-time-form/StoreTimeForm.stories.tsx
  app/(main)/store/register-store/_components/store-time-form/StoreTimeForm.tsx
  app/(main)/store/register-store/_constants/errorMessage.ts
  app/(main)/store/register-store/_constants/time.ts
  app/(main)/store/register-store/_utils/validate.ts
  app/(main)/store/register-store/store-info/page.tsx
  app/(main)/store/register-store/store-number/page.tsx
  app/(main)/store/register-store/store-time/page.tsx
  app/_assets/images/notification.png
  app/_components/Header/Header.tsx
  app/_constants/route.ts
  app/_utils/localstorage.ts
  package-lock.json
  package.json
  tailwind.config.ts
Labels: 기능

#95 react query 관련 세팅 작업
  .eslintrc.json
  .vscode/settings.json
  app/_components/main-temp/ApiTest.tsx
  app/_components/main-temp/QueryTest.tsx
  app/_hooks/query/tempTodo.ts
  app/_providers/QueryProvider.tsx
  app/error.tsx
  app/layout.tsx
  app/page.tsx
  package-lock.json
  package.json
Labels: 문서, 기능

#100 상품 api 관련 작업
  app/(main)/store/product-detail/[id]/page.tsx
  app/(main)/store/register-store/_components/store-time-form/StoreTimeForm.tsx
  app/_components/main-temp/MswTestButton.tsx
  app/_constants/route.ts
  app/_mocks/browser.js
  app/_mocks/handlers/handler.ts
  app/_mocks/handlers/handlers.ts
  app/_mocks/handlers/item/handler.ts
  app/_mocks/handlers/item/mock.ts
  app/_mocks/handlers/temp/handler.ts
  app/_mocks/server.js
  app/_types/api/item.ts
  app/page.tsx
  middleware.ts
Labels: 문서, 기능

#104 영업 상태 토글 컴포넌트 구현하기
  app/(main)/store/home/_components/business-status/BusinessStatus.stories.tsx
  app/(main)/store/home/_components/business-status/BusinessStatus.tsx
  app/(main)/store/home/page.tsx
  app/_components/toggle-switch/ToggleSwitch.stories.tsx
  app/_components/toggle-switch/ToggleSwitch.tsx
  package-lock.json
Labels: 기능

#107 업체 등록하기 모달창 띄우는 작업
  app/(main)/store/home/_components/register-modal/RegisterModal.tsx
  app/(main)/store/home/page.tsx
  app/(main)/store/register-store/_components/store-info-form/StoreInfoForm.tsx
  app/(main)/store/register-store/_components/store-num-form/StoreNumForm.tsx
  app/(main)/store/register-store/_components/store-time-form/StoreTimeForm.tsx
  app/_components/main-temp/StartLink.tsx
  app/_constants/path.ts
  app/_utils/localstorage.ts
Labels: 기능

#101 주문 내역 리스트 카드 컴포넌트 주문 내역 페이지 작업
  app/(main)/store/order-list/[id]/_components/order-list-card/OrderListCard.tsx
  app/(main)/store/order-list/[id]/_components/order-list-dropdown/OrderListDropDown.stories.tsx
  app/(main)/store/order-list/[id]/_components/order-list-dropdown/OrderListDropDown.tsx
  app/(main)/store/order-list/[id]/_components/order-list-modal/OrderListModal.stories.tsx
  app/(main)/store/order-list/[id]/_components/order-list-modal/OrderListModal.tsx
  app/(main)/store/order-list/[id]/_components/order-list/OrderList.tsx
  app/(main)/store/order-list/[id]/fetchOrderList.ts
  app/(main)/store/order-list/[id]/page.tsx
  app/_assets/images/polygon.png
  app/_assets/images/reversePolygon.png
  app/_components/Footer/Footer.tsx
  app/_components/infinite-scroll/InfiniteScrollList.stories.tsx
  app/_components/infinite-scroll/InfiniteScrollList.tsx
  app/_components/infinite-scroll/Items.tsx
  app/_components/infinite-scroll/LoadMoreItems.tsx
Labels: 기능

#106 feat: axios contextapi설정
  app/_providers/auth.tsx
  app/_services/auth/auth.ts
  app/layout.tsx
  package-lock.json
  package.json
Labels: 기능

#120 업체 측 주문 내역 페이지 리팩토링
  app/(main)/store/order-list/[id]/_components/order-list-dropdown/OrderListDropDown.tsx
  app/(main)/store/order-list/[id]/_components/order-list-modal/OrderListModal.tsx
  app/(main)/store/order-list/[id]/_components/order-list/OrderList.tsx
  app/_components/infinite-scroll/InfiniteScrollList.stories.tsx
  app/_components/infinite-scroll/InfiniteScrollList.tsx
  app/_components/infinite-scroll/LoadMoreItems.tsx
Labels: 리팩토링

#108 상품 api 와이어 프레임 작업
  app/(main)/customer/order-item/[id]/page.tsx
  app/(main)/store/edit-item/[id]/_components/ItemEdit.tsx
  app/(main)/store/edit-item/[id]/page.tsx
  app/(main)/store/edit-product/[id]/page.tsx
  app/(main)/store/item-detail/[id]/_components/Item.tsx
  app/(main)/store/item-detail/[id]/page.tsx
  app/(main)/store/product-detail/[id]/page.tsx
  app/(main)/store/register-item/page.tsx
  app/(main)/store/register-product/page.tsx
  app/_components/KakaoMap/KakaoMap.tsx
  app/_components/infinite-scroll/LoadMoreItems.tsx
  app/_components/main-temp/ApiTest.tsx
  app/_constants/path.ts
  app/_hooks/kakao-map/useGetMap.ts
  app/_hooks/query/item.ts
  app/_mocks/handlers/item/handler.ts
  app/_services/auth/auth.ts
  app/layout.tsx
  app/page.tsx
  public/mocks/MSWComponent.tsx
  public/mocks/MSWProvider.tsx
Labels: 문서, 기능

#119 스토리북 관련 설정 작업
  .storybook/main.ts
  .vscode/stories.tsx.code-snippets
  app/(main)/store/home/_components/business-status/BusinessStatus.stories.tsx
  app/(main)/store/home/_components/business-status/BusinessStatus.tsx
  app/(main)/store/home/_components/register-modal/RegisterModal.stories.tsx
  app/(main)/store/home/_components/register-modal/RegisterModal.tsx
  app/(main)/store/order-list/[id]/_components/order-list-dropdown/OrderListDropDown.stories.tsx
  app/(main)/store/order-list/[id]/_components/order-list-dropdown/OrderListDropDown.tsx
  app/(main)/store/order-list/[id]/_components/order-list-modal/OrderListModal.stories.tsx
  app/(main)/store/register-store/_components/store-info-form/StoreInfoForm.stories.tsx
  app/(main)/store/register-store/_components/store-num-form/StoreNumForm.stories.tsx
  app/(main)/store/register-store/_components/store-num-form/StoreNumForm.tsx
  app/(main)/store/register-store/_components/store-time-form/StoreTimeForm.stories.tsx
  app/(main)/store/register-store/_components/store-time-form/StoreTimeForm.tsx
  app/_components/AddressButton/AddressButton.stories.tsx
  app/_components/Footer/Footer.tsx
  app/_components/Footer/footer.stories.tsx
  app/_components/PrimaryButton/PrimaryButton.stories.tsx
  app/_components/infinite-scroll/InfiniteScrollList.stories.tsx
  app/_components/main-temp/ServiceIntro.stories.tsx
  app/_components/main-temp/ServiceIntro.tsx
  app/_components/main-temp/StartLink.stories.tsx
  app/_components/main-temp/StartLink.tsx
  app/_components/toggle-switch/ToggleSwitch.stories.tsx
  package-lock.json
  public/mocks/index.ts
Labels: 스타일, 기능

#122 안내사항 컴포넌트 구현
  app/_components/notification/Notification.stories.tsx
  app/_components/notification/Notification.tsx
  tailwind.config.ts
Labels: 기능

#124 배포 환경 api 연결 테스트
  app/_components/main-temp/ApiTest.tsx
Labels: 기능, 긴급

#123 장바구니 주문 정보 컴포넌트 구현
  app/(main)/customer/cart/[id]/_components/order-information/OrderInformation.stories.tsx
  app/(main)/customer/cart/[id]/_components/order-information/OrderInformation.tsx
  app/(main)/customer/cart/[id]/_constants/time.ts
  app/(main)/store/register-store/_components/store-info-form/StoreInfoForm.tsx
  app/(main)/store/register-store/_utils/validate.ts
  app/_components/notification/Notification.stories.tsx
  app/_constants/errorMessage.ts
  package-lock.json
  package.json
  tailwind.config.ts
Labels: 기능

#136 팝업 컴포넌트 구현
  app/_components/infinite-scroll/LoadMoreItems.tsx
  app/_components/pop-up/PopUp.stories.tsx
  app/_components/pop-up/PopUp.tsx
Labels: 스타일, 기능

#132 상품 관련 디자인 작업
  .storybook/preview.tsx
  .vscode/settings.json
  app/(main)/store/edit-item/[id]/_components/ItemEdit.tsx
  app/(main)/store/item-detail/[id]/_components/Item.tsx
  app/(main)/store/item-detail/[id]/_components/ItemDetail.stories.tsx
  app/(main)/store/item-detail/[id]/_components/ItemDetail.tsx
  app/(main)/store/item-detail/[id]/page.tsx
  app/(main)/store/item-edit/[id]/_components/ItemEdit.tsx
  app/(main)/store/item-edit/[id]/page.tsx
  app/(main)/store/item-register/_components/ItemRegister.stories.tsx
  app/(main)/store/item-register/_components/ItemRegister.tsx
  app/(main)/store/item-register/page.tsx
  app/(main)/store/register-item/page.tsx
  app/_assets/images/image-upload.png
  app/_assets/images/mock-donut.png
  app/_components/notification/Notification.tsx
  app/_config/_image/assets.ts
  app/_constants/path.ts
  app/layout.tsx
  app/page.tsx
Labels: 스타일

#134 refactor:헤더작업
  app/_components/Header/CustomerHeader.stories.tsx
  app/_components/Header/CustomerHeader.tsx
  app/_components/Header/Header.stories.tsx
  app/_components/Header/Header.tsx
  app/_components/Header/HeaderItem.tsx
  app/_components/Header/HeaderItemtext.tsx
  app/_components/Header/assets/dealight-emoji.svg
  app/_components/Header/assets/triangle.svg
  app/page.tsx
Labels: 리팩토링

#140 130 헤더 컴포넌트 -헤더컴포넌트 수정과 스토리북 경로 수정 , 파일수정
  app/_components/Header/CustomerHeader.stories.tsx
  app/_components/Header/CustomerHeader.tsx
  app/_components/Header/Header.stories.tsx
  app/_components/Header/Header.tsx
Labels: 리팩토링

#139 장바구니 리스트 컴포넌트 구현하기
  app/(main)/customer/cart/[id]/_components/cart-contents/CartContents.tsx
  app/(main)/customer/cart/[id]/_components/item-card/ItemCard.stories.tsx
  app/(main)/customer/cart/[id]/_components/item-card/ItemCard.tsx
  app/(main)/customer/cart/[id]/_components/item-list/ItemList.stories.tsx
  app/(main)/customer/cart/[id]/_components/item-list/ItemList.tsx
  app/(main)/customer/cart/[id]/_components/reset-button/ResetButton.tsx
  app/(main)/customer/cart/[id]/_types/CartCardType.ts
  app/(main)/customer/cart/[id]/page.tsx
  app/_assets/images/minus.png
  app/_assets/images/plus.png
  tailwind.config.ts
Labels: 기능

#144 고객 측 홈 페이지 오늘의 딜라잇 구현
  app/(main)/customer/home/_components/ItemCards.tsx
  app/(main)/customer/home/_components/TodayDealight.tsx
  app/(main)/customer/home/_components/TodayDealightDropDown.tsx
  app/(main)/customer/home/fetchData.ts
  app/(main)/customer/home/page.tsx
  app/_assets/images/donut.png
Labels: 스타일, 기능

#142 고객 마이페이지 구현
  app/(main)/customer/my-page/[id]/_components/MyPageContents/MyPageContents.stories.tsx
  app/(main)/customer/my-page/[id]/_components/MyPageContents/MyPageContents.tsx
  app/(main)/customer/my-page/[id]/_utils/validate.ts
  app/(main)/customer/my-page/[id]/page.tsx
  app/_components/Footer/Footer.tsx
  app/_components/SearchAddress/SearchAddress.tsx
  app/_constants/errorMessage.ts
  app/_hooks/useCoordinate.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: 기능

#143 인증 인가 로직 구성
  .env.local.example
  .storybook/preview.tsx
  app/(main)/customer/login/page.tsx
  app/(main)/customer/my-page/[id]/layout.tsx
  app/(main)/customer/sign-up/page.tsx
  app/(main)/customer/signup/page.tsx
  app/(main)/kakao/page.tsx
  app/(main)/store/home/layout.tsx
  app/(main)/store/home/page.tsx
  app/(main)/store/login/page.tsx
  app/(main)/store/sign-up/page.tsx
  app/(main)/store/signup/page.tsx
  app/_components/Header/CustomerHeader.tsx
  app/_components/Header/LoginHeader.tsx
  app/_components/layout/OnlyNotUserLayout.tsx
  app/_components/layout/OnlyStoreLayout.tsx
  app/_components/layout/OnlyUserLayout.tsx
  app/_components/main-temp/AuthTest.tsx
  app/_components/main-temp/StartLink.tsx
  app/_constants/path.ts
  app/_hooks/query/tempTodo.ts
  app/_providers/AuthProvider.tsx
  app/_providers/UserInfoProvider.tsx
  app/_providers/auth.tsx
  app/_services/apiClient.ts
  app/_utils/localstorage.ts
  app/layout.tsx
  app/page.tsx
Labels: 기능

#147 위도 경도 훅 구현하기
  app/(main)/customer/my-page/[id]/_components/MyPageContents/MyPageContents.tsx
  app/_hooks/useCoordinate.ts
Labels: 기능

#158 헤더 및 푸터 디자인 수정
  app/(main)/customer/home/page.tsx
  app/_assets/svgs/cart-icon.svg
  app/_assets/svgs/search-icon.svg
  app/_components/Footer/Footer.tsx
  app/_components/Header/CustomerHeader.tsx
  app/_components/Header/Header.tsx
  app/_components/Header/LoginHeader.tsx
  app/page.tsx
Labels: 스타일

#156 업체 등록하기 페이지 리팩토링
  app/(main)/customer/my-page/[id]/_components/MyPageContents/MyPageContents.tsx
  app/(main)/store/register-store/_components/store-info-form/StoreInfoForm.tsx
  app/(main)/store/register-store/_components/store-num-form/StoreNumForm.tsx
  app/(main)/store/register-store/_components/store-time-form/StoreTimeForm.tsx
  app/_hooks/useCoordinate.ts
Labels: 리팩토링

#159 업체 측 홈페이지 팝업 창 추가 작업
  app/_components/pop-up/PopUp.tsx
  app/_components/toggle-switch/ToggleSwitch.tsx
Labels: 기능

#154 sign up 페이지 코드 리펙토링
  app/(main)/store/sign-up/Components/GuildeText/GuideText.stories.tsx
  app/(main)/store/sign-up/Components/GuildeText/GuideText.tsx
  app/(main)/store/sign-up/Components/Signup/Signup.stories.tsx
  app/(main)/store/sign-up/Components/Signup/Signup.tsx
  app/(main)/store/sign-up/page.tsx
Labels: 버그, 기능, 리팩토링

#161 업체 측 상품 관리하기 페이지 컴포넌트 작업
  app/(main)/store/item-manage/[id]/_components/product-list/ItemCards.tsx
  app/(main)/store/item-manage/[id]/_components/product-list/ProductList.tsx
  app/(main)/store/item-manage/[id]/fetchData.ts
  app/(main)/store/item-manage/[id]/page.tsx
  app/_components/Footer/Footer.tsx
  app/_constants/path.ts
Labels: 스타일, 기능

#177 feat: 헤더 주솟값 전역 컨텍스트로 구현
  app/(main)/customer/home/page.tsx
  app/_components/Header/CustomerHeader.stories.tsx
  app/_components/Header/CustomerHeader.tsx
  app/_providers/AddressProvider.tsx
  app/layout.tsx
Labels: 기능

#166 업체 마이페이지 구현하기
  app/(main)/store/my-page/[id]/_components/image-uploader/ImageUploader.stories.tsx
  app/(main)/store/my-page/[id]/_components/image-uploader/ImageUploader.tsx
  app/(main)/store/my-page/[id]/_components/logout-button/LogoutButton.stories.tsx
  app/(main)/store/my-page/[id]/_components/logout-button/LogoutButton.tsx
  app/(main)/store/my-page/[id]/_components/my-page-form/MyPageForm.stories.tsx
  app/(main)/store/my-page/[id]/_components/my-page-form/MyPageForm.tsx
  app/(main)/store/my-page/[id]/_components/profile-information/ProfileInformation.tsx
  app/(main)/store/my-page/[id]/_components/store-information/StoreInformation.tsx
  app/(main)/store/my-page/[id]/page.tsx
Labels: 기능

#174 업체 등록 api 연결 및 업체 등록 여부 체크 후 라우팅 처리
  app/(main)/store/register-store/_components/store-info-form/StoreInfoForm.tsx
  app/(main)/store/register-store/_components/store-time-form/StoreTimeForm.tsx
  app/(main)/store/register-store/_services/patchRole.ts
  app/(main)/store/register-store/_services/postStore.ts
  app/(main)/store/register-store/layout.tsx
  app/_components/main-temp/AuthTest.tsx
  app/_providers/UserInfoProvider.tsx
Labels: 기능

#179 고객 측 홈페이지 api 작업
  app/(main)/customer/home/_components/ItemCards.tsx
  app/(main)/customer/home/_components/TodayDealight.tsx
  app/(main)/customer/home/_components/TodayDealightDropDown.tsx
  app/(main)/customer/home/_services/fetchData.ts
  app/(main)/customer/home/fetchData.ts
  app/(main)/customer/home/page.tsx
  app/_components/Header/CustomerHeader.tsx
Labels: 기능

#178 영업 상태 조회 api 연결
  app/(main)/store/home/_components/business-status/BusinessStatus.tsx
  app/(main)/store/home/_services/getStatus.ts
  app/(main)/store/register-store/_services/postStore.ts
Labels: 기능

#184 영업 상태 수정 api 연결하기
  app/(main)/store/home/_components/business-status/BusinessStatus.tsx
  app/(main)/store/home/_services/patchStatus.ts
  app/_components/toggle-switch/ToggleSwitch.tsx
Labels: 기능

#182 167 회원가입 api연결
  app/(main)/kakao/page.tsx
  app/(main)/store/sign-up/page.tsx
  app/(main)/store/signup/_components/GuildeText/GuideText.stories.tsx
  app/(main)/store/signup/_components/GuildeText/GuideText.tsx
  app/(main)/store/signup/_components/Signup/Signup.stories.tsx
  app/(main)/store/signup/_components/Signup/Signup.tsx
  app/(main)/store/signup/layout.tsx
  app/(main)/store/signup/page.tsx
  app/_constants/path.ts
  app/_providers/UserInfoProvider.tsx
Labels: 기능

#186 고객 측 주문 내역 페이지 api 연결 작업
  app/(main)/customer/order-list/[id]/_components/item-list/ItemList.tsx
  app/(main)/customer/order-list/[id]/_components/order-list-card/OrderListCard.tsx
  app/(main)/customer/order-list/[id]/_components/order-list-dropdown/OrderListDropDown.tsx
  app/(main)/customer/order-list/[id]/_components/order-list/OrderList.tsx
  app/(main)/customer/order-list/[id]/_services/getOrderList.ts
  app/(main)/customer/order-list/[id]/fetchOrderList.ts
Labels: 기능

#191 업체 상품 관련 api 작업
  app/(main)/customer/signup/page.tsx
  app/(main)/store/home/_components/home-buttons/HomeButton.tsx
  app/(main)/store/home/layout.tsx
  app/(main)/store/item-detail/[id]/_components/ItemDetail.stories.tsx
  app/(main)/store/item-detail/[id]/_components/ItemDetail.tsx
  app/(main)/store/item-detail/[id]/error.tsx
  app/(main)/store/item-detail/[id]/page.tsx
  app/(main)/store/item-edit/[id]/_components/ItemEdit.tsx
  app/(main)/store/item-edit/[id]/page.tsx
  app/(main)/store/item-register/_components/ItemRegister.tsx
  app/_components/main-temp/AuthTest.tsx
  app/_components/main-temp/MswTestButton.tsx
  app/_hooks/query/item.ts
  app/_mocks/browser.js
  app/_mocks/handlers/handlers.ts
  app/_mocks/handlers/item/handler.ts
  app/_mocks/handlers/item/mock.ts
  app/_mocks/handlers/temp/handler.ts
  app/_mocks/server.js
  app/_providers/AuthProvider.tsx
  app/_providers/UserInfoProvider.tsx
  app/_types/api/item.ts
  app/layout.tsx
  app/page.tsx
  next.config.js
  package-lock.json
  package.json
  public/mockServiceWorker.js
  public/mocks/MSWProvider.tsx
  public/mocks/index.ts
Labels: 기능

#195 footer 컴포넌트 업체측과 고객측으로 분리
  app/(main)/customer/cart/[id]/page.tsx
  app/(main)/customer/home/page.tsx
  app/(main)/customer/my-page/[id]/page.tsx
  app/(main)/customer/order-detail/[id]/_components/main-contents/MainContents.tsx
  app/(main)/customer/order-list/[id]/_components/order-list/OrderList.tsx
  app/(main)/store/home/page.tsx
  app/(main)/store/item-manage/[id]/page.tsx
  app/(main)/store/my-page/[id]/page.tsx
  app/(main)/store/order-detail/[id]/page.tsx
  app/(main)/store/order-list/[id]/_components/order-list/OrderList.tsx
  app/_components/Footer/CustomerFooter.tsx
  app/_components/Footer/Footer.tsx
  app/_components/Footer/StoreFooter.tsx
  app/_components/Footer/footer.stories.tsx
Labels: 기능

#193 고객 마이페이지 api 연결하기
  app/(main)/customer/my-page/[id]/_components/MyPageContents/MyPageContents.tsx
  app/(main)/customer/my-page/[id]/_services/getProfile.ts
  app/(main)/customer/my-page/[id]/_services/patchProfile.ts
  app/(main)/customer/my-page/[id]/_types/profileType.ts
  app/(main)/customer/my-page/[id]/layout.tsx
  app/(main)/store/register-store/layout.tsx
Labels: 기능

#201 feat: axios uri수정 닉네임 중복확인 추가
  app/(main)/customer/search/fetchdata.ts
  app/(main)/kakao/page.tsx
  app/(main)/store/signup/_components/Signup/Signup.tsx
  app/(main)/store/signup/layout.tsx
  app/_constants/path.ts
Labels: 기능, 긴급

#197 업체 측 홈페이지 api 연결 작업
  app/(main)/customer/home/_components/ItemCards.tsx
  app/(main)/store/home/_components/business-status/BusinessStatus.stories.tsx
  app/(main)/store/home/_components/business-status/BusinessStatus.tsx
  app/(main)/store/home/_components/home-buttons/HomeButton.tsx
  app/(main)/store/home/_components/main-contents/MainContents.tsx
  app/(main)/store/home/_components/product-list/ItemCards.tsx
  app/(main)/store/home/_components/product-list/ProductList.tsx
  app/(main)/store/home/_services/getItemList.ts
  app/(main)/store/home/_services/getStatus.ts
  app/(main)/store/home/fetchData.ts
  app/(main)/store/home/page.tsx
  app/_components/toggle-switch/ToggleSwitch.stories.tsx
  app/_components/toggle-switch/ToggleSwitch.tsx
Labels: 기능

#199 상품 관리하기 페이지 api연결 작업
  app/(main)/store/item-manage/[id]/_components/ItemCards.tsx
  app/(main)/store/item-manage/[id]/_components/ProductList.tsx
  app/(main)/store/item-manage/[id]/_services/getItemList.ts
  app/(main)/store/item-manage/[id]/fetchData.ts
  app/(main)/store/item-manage/[id]/page.tsx
Labels: 기능

#206 고객 주문 상세 페이지 구현하기
  app/(main)/customer/order-detail/[id]/_components/main-contents/MainContents.tsx
  app/(main)/customer/order-detail/[id]/_components/review-button/ReviewButton.tsx
  app/(main)/customer/order-detail/[id]/_services/cancelOrder.ts
  app/_components/order-result/OrderResult.tsx
  app/_services/order/getOrder.ts
Labels: 기능

#208 이미지 patch api 연결 완료
  app/(main)/store/my-page/[id]/_components/image-uploader/ImageUploader.tsx
  app/(main)/store/my-page/[id]/_services/patchImage.ts
Labels: 기능

#203 업체 측 주문내역 페이지 api 연결 작업
  app/(main)/customer/order-list/[id]/_components/order-list-card/OrderListCard.tsx
  app/(main)/store/order-list/[id]/_components/item-list/ItemList.tsx
  app/(main)/store/order-list/[id]/_components/order-list-card/OrderListCard.tsx
  app/(main)/store/order-list/[id]/_components/order-list-dropdown/OrderListDropDown.stories.tsx
  app/(main)/store/order-list/[id]/_components/order-list-dropdown/OrderListDropDown.tsx
  app/(main)/store/order-list/[id]/_components/order-list/OrderList.tsx
  app/(main)/store/order-list/[id]/_services/getOrderList.ts
  app/(main)/store/order-list/[id]/fetchOrderList.ts
Labels: 기능

#202 고객 상품 주문 페이지 관련 작업
  app/(main)/customer/cart/[id]/page.tsx
  app/(main)/customer/item-detail/[id]/_components/BottomButtons.tsx
  app/(main)/customer/item-detail/[id]/_components/ItemDetail.tsx
  app/(main)/customer/item-detail/[id]/page.tsx
  app/(main)/customer/login/page.tsx
  app/(main)/customer/order-detail/[id]/_components/main-contents/MainContents.tsx
  app/(main)/customer/order-list/[id]/_components/order-list/OrderList.tsx
  app/(main)/customer/search/page.tsx
  app/(main)/customer/store-detail/[id]/_components/ItemCards.tsx
  app/(main)/customer/store-detail/[id]/_components/StoreDetail.tsx
  app/(main)/customer/store-detail/[id]/_mocks/itemMock.ts
  app/(main)/customer/store-detail/[id]/_mocks/reviewMock.ts
  app/(main)/customer/store-detail/[id]/page.tsx
  app/(main)/store/home/_components/main-contents/MainContents.tsx
  app/(main)/store/home/page.tsx
  app/(main)/store/item-detail/[id]/_components/ItemDetail.tsx
  app/(main)/store/item-detail/[id]/page.tsx
  app/(main)/store/item-edit/[id]/_components/ItemEdit.tsx
  app/(main)/store/item-edit/[id]/page.tsx
  app/(main)/store/item-manage/[id]/page.tsx
  app/(main)/store/item-register/_components/ItemRegister.tsx
  app/(main)/store/item-register/page.tsx
  app/(main)/store/login/page.tsx
  app/(main)/store/my-page/[id]/_components/my-page-form/MyPageForm.tsx
  app/(main)/store/order-detail/[id]/_components/main-contents/MainContents.tsx
  app/(main)/store/order-list/[id]/_components/order-list/OrderList.tsx
  app/(main)/store/register-store/_components/store-info-form/StoreInfoForm.stories.tsx
  app/(main)/store/register-store/_components/store-num-form/StoreNumForm.stories.tsx
  app/(main)/store/register-store/_components/store-time-form/StoreTimeForm.stories.tsx
  app/(main)/store/register-store/store-info/page.tsx
  app/(main)/store/register-store/store-number/page.tsx
  app/(main)/store/register-store/store-time/page.tsx
  app/(main)/store/signup/page.tsx
  app/_components/Footer/CustomerFooter.tsx
  app/_components/Footer/Footer.tsx
  app/_components/Footer/StoreFooter.tsx
  app/_components/Header/CustomerHeader.tsx
  app/_components/Header/Header.tsx
  app/_components/KakaoMap/KakaoMap.tsx
  app/_components/main-temp/ApiTest.tsx
  app/_components/main-temp/AuthTest.tsx
  app/_components/main-temp/ServiceIntro.tsx
  app/_constants/path.ts
  app/_hooks/query/item.ts
  app/_hooks/query/store.ts
  app/_providers/UserInfoProvider.tsx
  app/_types/api/item.ts
  app/_types/api/store.ts
  app/_utils/number.ts
  app/layout.tsx
  app/page.tsx
  next.config.js
Labels: 스타일, 기능

#216 장바구니 담기 및 주문하기 버튼 구현 완료
  app/(main)/customer/cart/[id]/_services/postCart.ts
  app/(main)/customer/item-detail/[id]/_components/BottomButtons.tsx
  app/(main)/customer/item-detail/[id]/page.tsx
  app/_components/pop-up/CustomPopUp.stories.tsx
  app/_components/pop-up/CustomPopUp.tsx
Labels: 기능

#218 장바구니 페이지 구현하기
  app/(main)/customer/cart/[id]/_components/cart-contents/CartContents.tsx
  app/(main)/customer/cart/[id]/_components/item-card/ItemCard.tsx
  app/(main)/customer/cart/[id]/_components/item-list/ItemList.stories.tsx
  app/(main)/customer/cart/[id]/_components/item-list/ItemList.tsx
  app/(main)/customer/cart/[id]/_components/main-contents/MainContents.tsx
  app/(main)/customer/cart/[id]/_components/order-information/OrderInformation.stories.tsx
  app/(main)/customer/cart/[id]/_components/order-information/OrderInformation.tsx
  app/(main)/customer/cart/[id]/_components/reset-button/ResetButton.tsx
  app/(main)/customer/cart/[id]/_constants/time.ts
  app/(main)/customer/cart/[id]/_services/deleteCart.ts
  app/(main)/customer/cart/[id]/_services/getCart.ts
  app/(main)/customer/cart/[id]/_services/patchCart.ts
  app/(main)/customer/cart/[id]/_services/postOrder.ts
  app/(main)/customer/cart/[id]/_types/CartCardType.ts
  app/(main)/customer/cart/[id]/_types/CartType.ts
  app/(main)/customer/cart/[id]/_utils/sumTotalPrice.ts
  app/(main)/customer/cart/[id]/page.tsx
  app/(main)/customer/item-detail/[id]/_components/BottomButtons.tsx
  app/page.tsx
Labels: 기능

#214 리스트 시작 page수정 작업
  app/(main)/customer/home/_components/ItemCards.tsx
  app/(main)/customer/home/_components/TodayDealight.tsx
  app/(main)/customer/home/page.tsx
  app/(main)/customer/order-list/[id]/_components/item-list/ItemList.tsx
  app/(main)/customer/order-list/[id]/_components/order-list-dropdown/OrderListDropDown.tsx
  app/(main)/store/home/_components/home-buttons/HomeButton.tsx
  app/(main)/store/home/_components/main-contents/MainContents.tsx
  app/(main)/store/home/_components/product-list/ItemCards.tsx
  app/(main)/store/home/_components/product-list/ProductList.tsx
  app/(main)/store/item-manage/[id]/_components/ProductList.tsx
  app/(main)/store/order-list/[id]/_components/item-list/ItemList.tsx
  app/(main)/store/order-list/[id]/_components/order-list-dropdown/OrderListDropDown.tsx
  app/(main)/store/order-list/[id]/_components/order-list/OrderList.tsx
Labels: 기능

#219 feat: 헤더에 주소값 fetch api 적용
  app/_components/AddressButton/AddressButton.tsx
  app/_components/Header/CustomerHeader.tsx
  app/_hooks/useCoordinate.ts
  app/_providers/AddressProvider.tsx
  app/_providers/AuthProvider.tsx
  app/_providers/UserInfoProvider.tsx
Labels: 기능

#227 고객 주문 상세 페이지 - 주문 정보 로직 수정
  app/(main)/customer/order-detail/[id]/_components/main-contents/MainContents.tsx
  app/(main)/store/order-detail/[id]/_components/main-contents/MainContents.tsx
  app/_services/order/getOrder.ts
Labels: 기능

#224 주문하기 구현 및 리뷰 여부 반영하기
  app/(main)/customer/cart/[id]/_components/cart-contents/CartContents.tsx
  app/(main)/customer/cart/[id]/_components/item-card/ItemCard.stories.tsx
  app/(main)/customer/cart/[id]/_components/item-card/ItemCard.tsx
  app/(main)/customer/cart/[id]/_components/item-list/ItemList.tsx
  app/(main)/customer/cart/[id]/_components/main-contents/MainContents.tsx
  app/(main)/customer/cart/[id]/_components/order-information/OrderInformation.stories.tsx
  app/(main)/customer/cart/[id]/_components/order-information/OrderInformation.tsx
  app/(main)/customer/cart/[id]/_services/clearCart.ts
  app/(main)/customer/cart/[id]/_services/getCart.ts
  app/(main)/customer/cart/[id]/_services/patchCart.ts
  app/(main)/customer/cart/[id]/_services/postOrder.ts
  app/(main)/customer/item-detail/[id]/_components/BottomButtons.tsx
  app/(main)/customer/order-detail/[id]/_components/main-contents/MainContents.tsx
  app/(main)/customer/order-detail/[id]/_components/review-button/ReviewButton.tsx
  app/(main)/customer/order-detail/[id]/_components/review-button/ReviewWriteButton.tsx
Labels: 기능

#232 업체 측 주문 상세 페이지 api 연결 작업 고객 측 주문 상세 페이지 리스트 작업
  app/(main)/customer/home/_components/ItemCards.tsx
  app/(main)/customer/home/_components/TodayDealight.tsx
  app/(main)/customer/home/page.tsx
  app/(main)/customer/order-detail/[id]/_components/main-contents/MainContents.tsx
  app/(main)/customer/order-detail/[id]/_components/product-list/ItemCards.tsx
  app/(main)/customer/order-detail/[id]/_components/product-list/ProductList.tsx
  app/(main)/customer/order-detail/[id]/fetchData.ts
  app/(main)/customer/order-list/[id]/_components/item-list/ItemList.tsx
  app/(main)/customer/order-list/[id]/_components/order-list-card/OrderListCard.tsx
  app/(main)/store/home/_components/product-list/ProductList.tsx
  app/(main)/store/item-manage/[id]/_components/ProductList.tsx
  app/(main)/store/order-detail/[id]/_components/main-contents/MainContents.tsx
  app/(main)/store/order-detail/[id]/_components/product-list/ItemCards.tsx
  app/(main)/store/order-detail/[id]/_components/product-list/ProductList.tsx
  app/(main)/store/order-detail/[id]/_services/patchOrder.ts
  app/(main)/store/order-detail/[id]/fetchData.ts
  app/(main)/store/order-list/[id]/_components/item-list/ItemList.tsx
  app/(main)/store/order-list/[id]/_components/order-list-card/OrderListCard.tsx
Labels: 기능

#231 229 헤더 버그 수정
  app/_components/Header/CustomerHeader.tsx
  app/_providers/AddressProvider.tsx
  app/_providers/UserInfoProvider.tsx
Labels: 긴급

#236 고객 측 홈 페이지 주변 가게 위치 마커 찍는 작업
  app/(main)/customer/home/_components/TodayDealight.tsx
  app/(main)/customer/home/page.tsx
  app/(main)/store/home/_components/home-buttons/HomeButton.tsx
  app/(main)/store/order-detail/[id]/_components/main-contents/MainContents.tsx
  app/(main)/store/order-list/[id]/_components/order-list/OrderList.tsx
  app/favicon.ico
  app/layout.tsx
  public/icon.png
Labels: 기능

#230 feat:검색 페이지 api연결
  app/(main)/customer/search/_component/Itemcard/Itemcard.tsx
  app/(main)/customer/search/_component/order-list-Dropdown/SortlistDropdown.tsx
  app/(main)/customer/search/_component/searchbar/Searchbar.stories.tsx
  app/(main)/customer/search/_component/searchbar/Searchbar.tsx
  app/(main)/customer/search/_component/sort-option/SortOption.tsx
  app/(main)/customer/search/fetchdata.ts
  app/(main)/customer/search/page.tsx
  package.json
Labels: 기능

#241 에러 해결 및 수정
  app/(main)/customer/home/_components/TodayDealight.tsx
  app/(main)/customer/order-list/[id]/_components/item-list/ItemList.tsx
  app/(main)/customer/order-list/[id]/_components/order-list-card/OrderListCard.tsx
  app/(main)/store/item-manage/[id]/_components/ProductList.tsx
  app/(main)/store/order-list/[id]/_components/item-list/ItemList.tsx
  app/(main)/store/order-list/[id]/_components/order-list-card/OrderListCard.tsx
  package-lock.json
Labels: 버그, 리팩토링

#237 자잘한 오류 해결
  app/(main)/customer/cart/[id]/_components/cart-contents/CartContents.tsx
  app/(main)/customer/cart/[id]/_components/item-card/ItemCard.stories.tsx
  app/(main)/customer/cart/[id]/_components/item-card/ItemCard.tsx
  app/(main)/customer/cart/[id]/_components/item-list/ItemList.stories.tsx
  app/(main)/customer/cart/[id]/_components/item-list/ItemList.tsx
  app/(main)/customer/cart/[id]/_components/main-contents/MainContents.tsx
  app/(main)/customer/cart/[id]/_components/order-information/OrderInformation.tsx
  app/(main)/customer/cart/[id]/_services/clearCart.ts
  app/(main)/customer/cart/[id]/_services/patchCart.ts
  app/(main)/customer/cart/[id]/_utils/sumTotalPrice.ts
  app/(main)/customer/my-page/[id]/_components/MyPageContents/MyPageContents.tsx
  app/(main)/customer/order-detail/[id]/_components/main-contents/MainContents.tsx
  app/(main)/store/order-detail/[id]/_components/main-contents/MainContents.tsx
  app/(main)/store/register-store/_components/store-time-form/StoreTimeForm.tsx
  app/_services/member/patchMember.ts
Labels: 긴급, 리팩토링

#242 상품 관련 폼 작업, 좌표 관련 에러 작업
  app/(main)/customer/home/_components/ItemCards.tsx
  app/(main)/customer/home/_components/TodayDealight.tsx
  app/(main)/customer/home/_services/fetchData.ts
  app/(main)/customer/home/page.tsx
  app/(main)/customer/search/page.tsx
  app/(main)/store/home/_components/home-buttons/HomeButton.tsx
  app/(main)/store/home/_components/product-list/ItemCards.tsx
  app/(main)/store/home/_services/getItemList.ts
  app/(main)/store/item-detail/[id]/_components/ItemDetail.tsx
  app/(main)/store/item-edit/[id]/_components/ItemEdit.tsx
  app/(main)/store/item-edit/[id]/page.tsx
  app/(main)/store/item-register/_components/ItemRegister.tsx
  app/_components/Header/CustomerHeader.stories.tsx
  app/_components/Header/CustomerHeader.tsx
  app/_components/Header/Header.tsx
  app/_components/PrimaryButton/PrimaryButton.tsx
  app/_components/main-temp/AuthTest.tsx
  app/_hooks/query/item.ts
  app/_hooks/query/member.ts
  app/_hooks/useCoordinate.ts
  app/_providers/AddressProvider.tsx
  app/_providers/AuthProvider.tsx
  app/_providers/UserInfoProvider.tsx
  app/_utils/convert.ts
  app/globals.css
  app/layout.tsx
  app/page.tsx
Labels: 버그, 스타일, 기능

#253 bugfix: css 수정 페이지 1로 수정
  app/(main)/customer/search/_component/Itemcard/Itemcard.tsx
  app/(main)/customer/search/page.tsx
Labels: 버그

#249 bugfix: 버그수정 정규식 수정,에러 예외처리
  app/(main)/customer/signup/_components/sign-up/SignUp.tsx
  app/(main)/store/signup/_components/Signup/Signup.tsx
Labels: 버그

#256 버그 수정
  app/(main)/customer/cart/[id]/_components/cart-contents/CartContents.tsx
  app/(main)/customer/cart/[id]/_components/order-information/OrderInformation.tsx
  app/(main)/customer/my-page/[id]/_components/MyPageContents/MyPageContents.stories.tsx
  app/(main)/customer/my-page/[id]/_components/MyPageContents/MyPageContents.tsx
  app/(main)/customer/my-page/[id]/page.tsx
  app/(main)/customer/order-detail/[id]/_components/review-button/ReviewButton.tsx
  app/(main)/customer/order-detail/[id]/_components/review-button/ReviewWriteButton.tsx
  app/(main)/customer/store-detail/[id]/_components/StoreDetail.tsx
  app/(main)/store/my-page/[id]/_components/image-uploader/ImageUploader.stories.tsx
  app/(main)/store/my-page/[id]/_components/image-uploader/ImageUploader.tsx
  app/(main)/store/my-page/[id]/_components/my-page-form/MyPageForm.stories.tsx
  app/(main)/store/my-page/[id]/_components/my-page-form/MyPageForm.tsx
  app/(main)/store/my-page/[id]/_components/profile-information/ProfileInformation.tsx
  app/(main)/store/my-page/[id]/_components/store-information/StoreInformation.tsx
  app/(main)/store/my-page/[id]/_services/deleteImage.ts
  app/(main)/store/my-page/[id]/_services/getProfile.ts
  app/(main)/store/my-page/[id]/_services/patchImage.ts
  app/(main)/store/my-page/[id]/_services/patchProfile.ts
  app/(main)/store/my-page/[id]/_types/profileType.ts
  app/(main)/store/my-page/[id]/page.tsx
  app/(main)/store/register-store/_constants/time.ts
  app/(main)/store/store-manage/_components/StoreManage.tsx
  app/_hooks/query/member.ts
  app/_hooks/query/store.ts
  app/_providers/UserInfoProvider.tsx
  app/_services/member/getMember.ts
  app/_services/member/patchMember.ts
  app/_types/member/profileType.ts
  app/_types/store/storeType.ts
  app/globals.css
Labels: 버그, 긴급, 리팩토링

#259 지도 관련 리팩토링 작업
  app/(main)/customer/home/_components/TodayDealightDropDown.tsx
  app/(main)/customer/order-list/[id]/_components/order-list-dropdown/OrderListDropDown.tsx
  app/(main)/customer/search/_component/order-list-Dropdown/SortlistDropdown.tsx
  app/(main)/store/home/_components/product-list/ItemCards.tsx
  app/(main)/store/login/page.tsx
  app/(main)/store/order-list/[id]/_components/order-list-dropdown/OrderListDropDown.tsx
  app/(main)/store/order-list/[id]/_components/order-list-modal/OrderListModal.tsx
  app/(main)/store/order-list/[id]/_components/order-list/OrderList.tsx
  app/_assets/images/banner.png
  app/_assets/images/member-header-icon.png
  app/_assets/images/polygon.png
  app/_assets/images/reversePolygon.png
  app/_assets/svgs/.temp
  app/_assets/svgs/banner.svg
  app/_assets/svgs/polygon.svg
  app/_components/AddressButton/AddressButton.tsx
  app/_components/Header/CustomerHeader.tsx
  app/_components/Header/Header.tsx
  app/_components/Header/LoginHeader.tsx
  app/_components/SearchAddress/SearchAddress.tsx
  app/_components/main/AuthTest.tsx
  app/_components/main/ServiceIntro.stories.tsx
  app/_components/main/ServiceIntro.tsx
  app/_components/main/StartLink.stories.tsx
  app/_components/main/StartLink.tsx
  app/_hooks/useCoordinate.ts
  app/page.tsx
Labels: 스타일, 기능, 리팩토링

#260 254 리뷰 페이지
  app/(main)/customer/order-detail/[id]/_components/review-button/ReviewButton.tsx
  app/(main)/customer/order-detail/[id]/_components/review-button/ReviewWriteButton.tsx
  app/(main)/customer/review-write/[id]/page.tsx
  app/(main)/customer/review-write/[orderId]/page.tsx
  app/(main)/customer/review-write/assets/delight-emoji.svg
  app/(main)/customer/review/[id]/page.tsx
  app/(main)/customer/review/_component/messagecard/MessageCard.tsx
  app/(main)/customer/review/assets/delight-emoji.svg
  app/(main)/customer/search/_component/Itemcard/Itemcard.tsx
  app/(main)/customer/search/_component/order-list-Dropdown/SortlistDropdown.tsx
  app/(main)/customer/search/page.tsx
  app/(main)/customer/signup/_components/sign-up/SignUp.tsx
  app/(main)/customer/signup/page.tsx
  app/(main)/store/signup/_components/Signup/Signup.tsx
Labels: 기능, 리팩토링

#261 디자인 수정 및 코드 리팩토링
  app/(main)/customer/cart/[id]/_components/item-card/ItemCard.tsx
  app/(main)/customer/login/page.tsx
  app/(main)/customer/order-detail/[id]/_components/main-contents/MainContents.tsx
  app/(main)/customer/signup/_components/sign-up/SignUp.tsx
  app/(main)/store/login/page.tsx
  app/(main)/store/signup/_components/Signup/Signup.tsx
  app/_assets/svgs/banner.svg
  app/_assets/svgs/customer-icon.svg
  app/_assets/svgs/intro-1.svg
  app/_assets/svgs/intro-2.svg
  app/_assets/svgs/intro-3.svg
  app/_assets/svgs/kakao.svg
  app/_assets/svgs/store-icon.svg
  app/_components/PrimaryButton/PrimaryButton.tsx
  app/_components/main/ServiceIntro.tsx
  app/_components/main/StartLink.tsx
  app/page.tsx
Labels: 스타일, 리팩토링

#269 스타일 수정 및 코드 리팩토링
  app/(main)/customer/cart/[id]/_components/item-card/ItemCard.tsx
  app/(main)/customer/cart/[id]/_components/order-information/OrderInformation.tsx
  app/_components/order-result/OrderResult.tsx
Labels: 버그, 스타일

#270 스타일 수정 및 코드 리팩토링
  app/(main)/customer/cart/[id]/_components/cart-contents/CartContents.tsx
  app/(main)/customer/cart/[id]/_components/item-card/ItemCard.tsx
  app/(main)/customer/cart/[id]/_components/order-information/OrderInformation.tsx
  app/(main)/customer/cart/[id]/_constants/time.ts
  app/(main)/store/my-page/[id]/_components/store-information/StoreInformation.tsx
  app/(main)/store/register-store/_components/store-time-form/StoreTimeForm.tsx
  app/(main)/store/register-store/_constants/time.ts
Labels: 스타일, 리팩토링
